version: 2

build:
  os: ubuntu-20.04
  tools:
    python: '3.7'
  apt_packages:
    - graphviz

sphinx:
  fail_on_warning: true

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs

formats: []
