version: 2

build:
  os: ubuntu-20.04
  apt_packages:
    - graphviz
  tools:
    python: "3.7"

sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: true

python:
  system_packages: false
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
        - all

formats: []
