name: Mirror Examples
on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * *'
jobs:
  examples:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        repository: skypyproject/examples
        token: ${{ secrets.EXAMPLES_TOKEN }}
        fetch-depth: 0
    - name: Configure git
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git config advice.detachedHead false
    - name: Clone SkyPy
      run: |
        pushd ..

        git clone https://github.com/skypyproject/skypy.git
        cd skypy
        branches=$(git branch --format='%(refname:short)')
        tags=$(git tag)

        popd

        echo "branches: $(echo ${branches})"
        echo "::set-env name=branches::$(echo ${branches})"

        echo "tags: $(echo ${tags})"
        echo "::set-env name=tags::$(echo ${tags})"
    - name: Mirror Branches
      run: |
        for b in ${branches}; do
          (git checkout -qf ${b} 2> /dev/null && echo "checkout ${b}") || (git checkout -qf --orphan ${b} && echo "branch ${b}")
          git rm -qrf .
          cd ../skypy && git checkout -qf ${b} && cd -
          cp -a $(find ../skypy -maxdepth 2 -name LICENSE.rst) .
          cp -a ../skypy/examples/* .
          git add -Af
          git checkout master -- README.md
          git diff --cached --quiet || git commit -qm "branch ${b}"
        done
        git push -f --all origin
    - name: Mirror Tags
      run: |
        for t in ${tags}; do
          (git checkout -qf ${t} 2> /dev/null && echo "checkout ${t}") || (git checkout -qf --orphan ${t} && echo "tag ${t}")
          git rm -qrf .
          cd ../skypy && git checkout -qf ${t} && cd -
          cp -a $(find ../skypy -maxdepth 2 -name LICENSE.rst) .
          cp -a ../skypy/examples/* .
          git add -Af
          git checkout master -- README.md
          git diff --cached --quiet || git commit -qm "tag ${t}"
          git tag -f ${t}
        done
        git push -f --tags origin
