name: Code Style
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Install Python 3.5
      uses: actions/setup-python@v1
      with:
        python-version: 3.5
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 "setuptools>=30.3"
    - name: Add flake8 Matcher
      run: |
        echo ::add-matcher::.github/problem_matchers/flake8.json
    - name: Run flake8
      run: |
        python setup.py flake8
