name: Unit Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.5
      uses: actions/setup-python@v1
      with:
        python-version: 3.5
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install astropy pytest pytest-astropy scipy "setuptools>=30.3"
    - name: Run Tests
      run: |
        python setup.py test
